#connection_recycle_time is set to 300sec in order not to hit into conntrack timeouts (PRODX-1179, PRODX-1170)
# Optimized for the following cloud configuration
# controllers: 3
# computes: <10
features:
  messaging:
    components_with_dedicated_messaging:
      - networking
services:
  database:
    mariadb:
      values:
        conf:
          ingress_conf:
            proxy-buffer-size: "20m"
            proxy-connect-timeout: "600"
          phy_backup:
            backup_timeout: 3600
        volume:
          phy_backup:
            size: "20Gi"
  identity:
    keystone:
      values:
        pod:
          replicas:
            api: 3
          lifecycle:
            upgrades:
              deployments:
                pod_replacement_strategy: RollingUpdate
                rolling_update:
                  max_unavailable: 10%
                  max_surge: 10%
        conf:
          keystone:
            database:
              max_pool_size: 10
              max_retries: -1
              max_overflow: 30
              connection_recycle_time: 300
            oslo_messaging_rabbit:
              rabbit_qos_prefetch_count: 64
  key-manager:
    barbican:
      values:
        pod:
          replicas:
            api: 3
          lifecycle:
            upgrades:
              deployments:
                pod_replacement_strategy: RollingUpdate
                rolling_update:
                  max_unavailable: 10%
                  max_surge: 10%
  image:
    glance:
      values:
        pod:
          replicas:
            api: 3
            registry: 3
          lifecycle:
            upgrades:
              deployments:
                pod_replacement_strategy: RollingUpdate
                rolling_update:
                  max_unavailable: 10%
                  max_surge: 10%
        conf:
          glance:
            DEFAULT:
              workers: 1
            database:
              max_pool_size: 10
              max_retries: -1
              max_overflow: 30
              connection_recycle_time: 300
            oslo_messaging_rabbit:
              rabbit_qos_prefetch_count: 64
  compute:
    nova:
      values:
        pod:
          replicas:
            api_metadata: 3
            osapi: 3
            conductor: 3
            consoleauth: 3
            scheduler: 3
            novncproxy: 3
            placement: 3
            compute_ironic: 3
          lifecycle:
            upgrades:
              daemonsets:
                pod_replacement_strategy: RollingUpdate
                compute:
                  # upgrade computes in butches with 10% of hosts from maximum
                  max_unavailable: 10%
              deployments:
                pod_replacement_strategy: RollingUpdate
                rolling_update:
                  max_unavailable: 10%
                  max_surge: 10%
        conf:
          nova:
            DEFAULT:
              cpu_allocation_ratio: 8.0
              ram_allocation_ratio: 1.1
              disk_allocation_ratio: 1.6
              metadata_workers: 1
              osapi_compute_workers: 1
              block_device_allocate_retries: 600
              block_device_allocate_retries_interval: 10
              report_interval: 60
              service_down_time: 180
              rpc_response_timeout: 30
            api_database:
              max_pool_size: 10
              max_retries: -1
              max_overflow: 30
              connection_recycle_time: 300
            cell0_database:
              max_pool_size: 10
              max_retries: -1
              max_overflow: 30
              connection_recycle_time: 300
            database:
              max_pool_size: 10
              max_retries: -1
              max_overflow: 30
              connection_recycle_time: 300
            placement_database:
              max_pool_size: 10
              max_retries: -1
              max_overflow: 30
              connection_recycle_time: 300
            conductor:
              workers: 1
            scheduler:
              workers: 1
            neutron:
              timeout: 300
            filter_scheduler:
              host_subset_size: 30
            oslo_messaging_rabbit:
              rabbit_qos_prefetch_count: 64
  networking:
    neutron:
      values:
        pod:
          replicas:
            server: 3
          lifecycle:
            upgrades:
              deployments:
                pod_replacement_strategy: RollingUpdate
                rolling_update:
                  max_unavailable: 10%
                  max_surge: 10%
              daemonsets:
                pod_replacement_strategy: RollingUpdate
                dhcp_agent:
                  max_unavailable: 1
                l3_agent:
                  max_unavailable: 1
                lb_agent:
                  max_unavailable: 10%
                metadata_agent:
                  max_unavailable: 10%
                ovs_agent:
                  max_unavailable: 10%
                sriov_agent:
                  max_unavailable: 10%
        conf:
          neutron:
            DEFAULT:
              dhcp_lease_duration: 86400
              rpc_workers: 4
              api_workers: 4
              rpc_state_report_workers: 2
              agent_down_time: 30
              max_l3_agents_per_router: 2
              executor_thread_pool_size: 70
            agent:
              report_interval: 10
            database:
              max_pool_size: 10
              max_retries: -1
              max_overflow: 70
              connection_recycle_time: 300
            oslo_messaging_rabbit:
              rabbit_qos_prefetch_count: 64
    openvswitch:
      values:
        pod:
          lifecycle:
            upgrades:
              daemonsets:
                pod_replacement_strategy: RollingUpdate
                ovs_db:
                  max_unavailable: 1
                ovs_vswitchd:
                  max_unavailable: 1
  block-storage:
    cinder:
      values:
        pod:
          replicas:
            api: 3
            scheduler: 3
            volume: 3
          lifecycle:
            upgrades:
              deployments:
                pod_replacement_strategy: RollingUpdate
                rolling_update:
                  max_unavailable: 10%
                  max_surge: 10%
        conf:
          cinder:
            DEFAULT:
              rpc_response_timeout: 3600
              osapi_volume_workers: 1
              backup_workers: 1
            database:
              max_pool_size: 10
              max_retries: -1
              max_overflow: 30
              connection_recycle_time: 300
            oslo_messaging_rabbit:
              rabbit_qos_prefetch_count: 64
  orchestration:
    heat:
      values:
        pod:
          replicas:
            cfn: 3
            api: 3
            engine: 3
          lifecycle:
            upgrades:
              deployments:
                pod_replacement_strategy: RollingUpdate
                rolling_update:
                  max_unavailable: 10%
                  max_surge: 10%
        conf:
          heat:
            DEFAULT:
              rpc_response_timeout: 600
              num_engine_workers: 1
              max_resources_per_stack: '20000'
              max_template_size: '5440000'
              max_json_body_size: '10880000'
            heat_api:
              workers: 1
            heat_api_cfn:
              workers: 1
            heat_api_cloudwatch:
              workers: 1
            database:
              max_pool_size: 10
              max_retries: -1
              max_overflow: 30
              connection_recycle_time: 300
            oslo_messaging_rabbit:
              rabbit_qos_prefetch_count: 64
  placement:
    placement:
      values:
        pod:
          replicas:
            api: 3
          lifecycle:
            upgrades:
              deployments:
                pod_replacement_strategy: RollingUpdate
                rolling_update:
                  max_unavailable: 10%
                  max_surge: 10%
  load-balancer:
    octavia:
      values:
        pod:
          replicas:
            api: 3
          lifecycle:
            upgrades:
              deployments:
                pod_replacement_strategy: RollingUpdate
                rolling_update:
                  max_unavailable: 10%
                  max_surge: 10%
              daemonsets:
                pod_replacement_strategy: RollingUpdate
                health_manager:
                  max_unavailable: 10%
        conf:
          octavia:
            database:
              max_pool_size: 10
              max_retries: -1
              max_overflow: 30
              connection_recycle_time: 300
            controller_worker:
              amp_active_retries: 100
              amp_active_wait_sec: 2
              workers: 1
            haproxy_amphora:
              connection_max_retries: 1500
              connection_retry_interval: 1
              rest_request_conn_timeout: 10
              rest_request_read_timeout: 120
            task_flow:
              engine: parallel
              max_workers: 64
            house_keeping:
              amphora_expiry_age: 3600
              load_balancer_expiry_age: 3600
            oslo_messaging_rabbit:
              rabbit_qos_prefetch_count: 64
  dns:
    designate:
      values:
        pod:
          replicas:
            api: 3
            central: 3
            mdns: 3
            producer: 3
            sink: 3
            worker: 3
          lifecycle:
            upgrades:
              deployments:
                pod_replacement_strategy: RollingUpdate
                rolling_update:
                  max_unavailable: 10%
                  max_surge: 10%
        conf:
          designate:
            service:api:
              workers: 1
  dashboard:
    horizon:
      values:
        pod:
          replicas:
            server: 2
          lifecycle:
            upgrades:
              deployments:
                pod_replacement_strategy: RollingUpdate
                rolling_update:
                  max_unavailable: 10%
                  max_surge: 10%
        conf:
          software:
            apache2:
              processes: 3
              threads: 10
  baremetal:
    ironic:
      values:
        pod:
          replicas:
            api: 3
            conductor: 3
        conf:
          ironic:
            database:
              max_pool_size: 10
              max_retries: -1
              max_overflow: 30
              connection_recycle_time: 300
  alarming:
    aodh:
      values:
        pod:
          replicas:
            api: 3
            evaluator: 3
            listener: 3
            notifier: 3
        conf:
          aodh:
            database:
              connection_recycle_time: 300
              max_overflow: 30
              max_pool_size: 10
  metric:
    gnocchi:
      values:
        pod:
          replicas:
            api: 3
        conf:
          gnocchi:
            database:
              connection_recycle_time: 300
              max_overflow: 30
              max_pool_size: 10
  event:
    panko:
      values:
        pod:
          replicas:
            api: 3
  metering:
    ceilometer:
      values:
        pod:
          replicas:
            central: 3
            collector: 3
            notification: 3
timeouts:
  application_readiness:
    nova:
      timeout: 600
      delay: 10
    neutron:
      timeout: 600
      delay: 10
    openvswitch:
      timeout: 600
      delay: 10
