# permissions for end users to view floatingips.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: floatingip-viewer-role
rules:
- apiGroups:
  - open4k.amadev.ru
  resources:
  - floatingips
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - open4k.amadev.ru
  resources:
  - floatingips/status
  verbs:
  - get
