# permissions for end users to edit images.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: image-editor-role
rules:
- apiGroups:
  - open4k.amadev.ru
  resources:
  - images
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - open4k.amadev.ru
  resources:
  - images/status
  verbs:
  - get
