# permissions for end users to view ports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: port-viewer-role
rules:
- apiGroups:
  - open4k.amadev.ru
  resources:
  - ports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - open4k.amadev.ru
  resources:
  - ports/status
  verbs:
  - get
