# permissions for end users to edit ports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: port-editor-role
rules:
- apiGroups:
  - open4k.amadev.ru
  resources:
  - ports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - open4k.amadev.ru
  resources:
  - ports/status
  verbs:
  - get
