
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - open4k.amadev.ru
  resources:
  - flavors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - open4k.amadev.ru
  resources:
  - flavors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - open4k.amadev.ru
  resources:
  - images
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - open4k.amadev.ru
  resources:
  - images/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - open4k.amadev.ru
  resources:
  - instances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - open4k.amadev.ru
  resources:
  - instances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - open4k.amadev.ru
  resources:
  - networks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - open4k.amadev.ru
  resources:
  - networks/status
  verbs:
  - get
  - patch
  - update
