#apiVersion: lcm.mirantis.com/v1alpha1
#kind: HelmBundle

{%- set stacklight_enabled = spec.get('features', {}).get('stacklight', {}).get('enabled', False) %}
{%- set backup_params = spec.get('features', {}).get('database', {}).get('backup', {}) %}

spec:
  releases:
  - name: openstack-mariadb
    chart: {{spec.common.infra.repo}}/mariadb
    values:
      conf:
        database_conf:
          mysqld:
            wsrep_provider_options:
              # Controls parallel applying of slave actions.
              # When enabled allows full range of parallelization as determined by certification algorithm.
              # When disabled limits parallel applying window to not exceed that seen on master.
              # In other words, the action starts applying no sooner than all actions it has seen on the master are committed.
              # The default value is YES, and it causes the issue described - here https://jira.mariadb.org/browse/MDEV-22766
              # Once the issue is fixed, this can be removed. Option can be set only starting galera 3.25.
              cert.optimistic_pa: "NO"
        phy_backup:
          backup_type: {{ backup_params.get('backup_type', 'incremental') }}
          {%- if backup_params.get('full_backup_cycle') %}
          full_backup_cycle: {{ backup_params['full_backup_cycle'] }}
          {%- endif %}
          {%- if backup_params.get('backups_to_keep') %}
          backups_to_keep: {{ backup_params['backups_to_keep'] }}
          {%- endif %}
      images:
        tags:
{%- for image in [
    "ingress",
    "prometheus_create_mysql_user",
    "image_repo_sync",
    "error_pages",
    "mariadb_backup",
    "mariadb_phy_backup",
    "mariadb_phy_restore",
    "prometheus_mysql_exporter",
    "prometheus_mysql_exporter_helm_tests",
    "dep_check",
    "mariadb",
    "mariadb_scripted_test",
    "mariadb_controller",] %}
        {%- if image in images %}
          {{ image }}: {{ images[image] }}
        {%- endif %}
{%- endfor %}
{%- if stacklight_enabled %}
      monitoring:
        prometheus:
          enabled: true
{%- endif %}
      manifests:
        network_policy: false
        job_cluster_wait: true
        cron_job_mariadb_phy_backup: true
        # Disable ingress controller in favor of mariadb-controller
        configmap_ingress_conf: false
        configmap_ingress_etc: false
        deployment_ingress: false
        deployment_error: false
        service_ingress: false
        deployment_controller: true
        service_master: true
      endpoints:
        cluster_domain_suffix: {{ spec.internal_domain_name }}
        oslo_db:
          namespace: null
          auth:
            admin:
              username: {{ admin_creds.database.username }}
              password: {{ admin_creds.database.password }}
            sst:
              username: {{ galera_creds.sst.username }}
              password: {{ galera_creds.sst.password }}
            exporter:
              username: {{ galera_creds.exporter.username }}
              password: {{ galera_creds.exporter.password }}
            audit:
              username: {{ galera_creds.audit.username }}
              password: {{ galera_creds.audit.password }}
            mariabackup:
              username: {{ galera_creds.backup.username }}
              password: {{ galera_creds.backup.password }}
      jobs:
        phy_backup_mariadb:
          cron: "{{ backup_params.get('schedule_time', '0 1 * * *') }}"
          suspend: {{ not backup_params.get('enabled', false) }}
      pod:
        replicas:
          server: 3
{%- if spec.get('features', {}).get('database', {}).get('local_volumes', {}).get('enabled', False) %}
        # To have higher level of data redundency in case of local volumes - ensure pods are spread
        # across volumes placed on different nodes
        affinity:
          anti:
            type:
              default: requiredDuringSchedulingIgnoredDuringExecution
{%- endif %}
      volume:
{%- if spec.get('features', {}).get('database', {}).get('local_volumes', {}).get('enabled', False) %}
        class_name: {{ spec.get('local_volume_storage_class', 'lvp-fake-root') }}
{%- else %}
        class_name: {{ spec.get('persistent_volume_storage_class', 'mirablock-k8s-block-hdd') }}
{%- endif %}
        phy_backup:
          class_name: {{ spec.get('persistent_volume_storage_class', 'mirablock-k8s-block-hdd') }}
          enabled: true
