---
apiVersion: v1
kind: Secret
metadata:
  name: open4k
type: Opaque
stringData:
  clouds.yaml: |
    clouds:
      devstack:
        project_domain_id: default
        region_name: RegionOne
        user_domain_name: Default
        project_name: admin
        identity_api_version: 3
        interface: public
        auth:
          username: admin
          password: stack
          auth_url: http://192.168.110.10/identity
