# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/open4k.amadev.ru_clouds.yaml
- bases/open4k.amadev.ru_instances.yaml
- bases/open4k.amadev.ru_flavors.yaml
- bases/open4k.amadev.ru_images.yaml
- bases/open4k.amadev.ru_networks.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_clouds.yaml
#- patches/webhook_in_instances.yaml
#- patches/webhook_in_flavors.yaml
#- patches/webhook_in_images.yaml
#- patches/webhook_in_networks.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_clouds.yaml
#- patches/cainjection_in_instances.yaml
#- patches/cainjection_in_flavors.yaml
#- patches/cainjection_in_images.yaml
#- patches/cainjection_in_networks.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
