---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openstack-controller.name" . }}-deploy-resources-bin
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
{{- $context := . }}
{{- range $resource := tuple "10-namespaces.yaml" "22-kopfpeering-crd.yaml" "23-openstackdeployment-crd.yaml" "50_kopfpeering.yaml" }}
  {{ $resource }}: |
  {{- $fname := printf "resources_shared/_%s.tpl" $resource }}
{{ tuple  $fname $context | include "template"  | indent 4 }}

{{- end }}
