---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openstack-controller.fullname" . }}-resources
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "openstack-controller.fullname" . }}-resources
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": "before-hook-creation"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ include "openstack-controller.fullname" . }}-resources
    namespace: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/name: {{ include "openstack-controller.name" . }}
    helm.sh/chart: {{ include "openstack-controller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  name: {{ include "openstack-controller.name" . }}-ensure-resources
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    spec:
      serviceAccountName: {{ include "openstack-controller.fullname" . }}-resources
      restartPolicy: OnFailure
      containers:
      - name: main
        command:
          - osctl-ensure-shared-resources
        image: {{ tuple . .Values.image | include "getImageUrl" }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/resources
          name: deploy-resources-bin
          readOnly: true
      volumes:
      - name: deploy-resources-bin
        configMap:
          name: {{ include "openstack-controller.name" . }}-deploy-resources-bin
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
